version: "3.8"

services:  
  web-laravel:  
    restart: always
    build: 
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:  
      - ./atcc-laravel:/var/www/html

  db-acme:
    container_name: db-acme
    image: postgres:14.5-alpine3.16  
    restart: always
    ports:
      - 3232:5432
    environment:  
      POSTGRES_PASSWORD: postgres  
      POSTGRES_DB: acme  
    volumes:  
      - "./.docker/dbdata:/var/lib/postgresql/data"

  nginx:  
    build: ./.docker/nginx  
    restart: always
    ports:  
      - 8000:80
    volumes:  
      - ./atcc-laravel/public:/var/www/html/public
    depends_on:  
      - web-laravel